nome = str(input('Informe o seu nome: ')).strip()
print('Analisando...')
print('O seu nome minusculo é {}'.format(nome.lower()))
print('O seu nome maiusculo é {}'.format(nome.upper()))
print('O seu nome possui {} letras'.format(len(nome)))
print('O seu primeiro nome possui {}'.format(nome.find(' ')))
print('O seu nome possui a letra {}'.format(nome.count('a')))
print('O nome nome {}'.format(nome.index('')))
print('O seu nome possui {}'.format(nome.capitalize()))
